### ISSUE TITLE
Add theme to the site

### ISSUE THREAD

**Issue by zenorocha** [dracula/oracle-sql-developer#1]
Hey @apercova, I just wanted to let you know that this theme is on the site now: https://draculatheme.com/oracle-sql-developer

Thanks for doing this theme!

**Comment by apercova** [comment]
Hi @zenorocha I've enjoyed making it. 
That's great to finally included it on darcula's site!

**Comment by zenorocha** [comment]
Yeah! That's super exciting. Thank you so much for doing it and thanks for your patience.
