### ISSUE TITLE
Save edit file xml but when ever restart Oracle the file remain unedited

### ISSUE THREAD

**Issue by hypntzed78** [dracula/oracle-sql-developer#7]
Save edit file xml but when ever restart Oracle the file remain unedited, how to fix this?
Have added dracula to this file, increase file size but  the file remain unedited after i restart the app 

![image](https://user-images.githubusercontent.com/57439364/171389068-4acaff9d-a6fd-4026-a710-2af806d0dfb7.png)

**Comment by vm7md98** [comment]
Just close sqldeveloper before installing Dracula theme.
